name: wflow

channels:
  - conda-forge
  - defaults

dependencies:
  - python=2.7
  - numpy=1
  - scipy=1
  - gdal=2
  - rasterio=1
  - fiona=1
  - netcdf4=1.3.1
  - pyproj=1
  - thrift=0.11
  - pyinstaller=3.3
  - versioneer=0.18
  - pywin32=221
  - setuptools=38
  - geojson=2
  - requests=2
  - click=6
  - shapely=1
  - pip=9
  - pip:
    - bmi-python
